# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-31 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='location',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
